---
name: Build Fedora CoreOS image

on:
  push:
    branches:
      - main
    tags:
      - v*
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  setup_build_environment:
    name: Setup build environment on gcloud
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '316.0.0'
          service_account_key: ${{ secrets.GCS_ASSEMBLER_SA }}
          export_default_credentials: true

      - name: Perform Terraform apply in CI script
        uses: docker://proum/terraform:v0.13.4-gcloud
        with:
          entrypoint: ""
          args: bash ci/scripts/create-build-env.sh --run-id ${GITHUB_RUN_ID}

  build_image:
    name: Build metal image
    needs: setup_build_environment
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        uses: docker://proum/terraform:v0.13.4-gcloud
        with:
          entrypoint: ""
          args: bash ci/scripts/build-coreos.sh --run-id ${GITHUB_RUN_ID}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: builds/*

  destroy_build_environment:
    name: Destroy build environment on gcloud
    needs:
      - setup_build_environment
      - build_image
    if: "always()"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '316.0.0'
          service_account_key: ${{ secrets.GCS_ASSEMBLER_SA }}
          export_default_credentials: true

      - name: Perform Terraform apply in CI script
        uses: docker://proum/terraform:v0.13.4-gcloud
        with:
          entrypoint: ""
          args: bash ci/scripts/destroy-build-env.sh --run-id ${GITHUB_RUN_ID}